### ISSUE TITLE
collapsible not a function, script.js, line:91

### ISSUE THREAD

**Issue by 1123581** [Luminous-Roleplay/LRP_Stable#3]
$('.collapsible').collapsible(); not a function? having a hard time figuring this one out. the menu wouldn't even open when i first added it, i fixed those issues and got the menu showing up but still working on this issue
![Untitled](https://user-images.githubusercontent.com/47376876/97066406-df364000-157a-11eb-8c0c-c70988459523.png)

**Comment by klandestino7** [comment]
The script name must be LRP_Stable
